# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../../src/AppBundle/{Entity,Repository,Tests,version.php,config.php,Controller/ui,Service/HttpHelper.php}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\api\:
        resource: '../../../src/AppBundle/Controller/api'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    #UI - guzzle client service for invoking api endpoints
    GuzzleHttp\Client:
        arguments:
            -
              http_errors: false
    
  
    #OAuthHelperService
    AppBundle\Service\OAuthHelper:
        public: true
        arguments:
            $database_host: "%database_host%"
            $database_name: "%database_name%"
            $database_user: "%database_user%"
            $database_password: "%database_password%"
    #PdoService
    AppBundle\Service\PdoHelper:
        public: true
        arguments:
            $database_host: "%database_host%"
            $database_name: "%database_name%"
            $database_user: "%database_user%"
            $database_password: "%database_password%"
    #Monolog DB Handler
    cspro_monolog_handler:
        class: AppBundle\Service\CSProMySQLHandler
        autowire: true
        public: true
        arguments:
            $level: "%csweb_db_log_level%"

     #ApiKeyUserProvider 
    AppBundle\Security\ApiKeyUserProvider:
        public: true
   
    #ApiAccessDeniedHandler 
    AppBundle\Security\ApiAccessDeniedHandler:
        public: true
        
    #DictionaryVoter
    AppBundle\Security\DictionaryVoter:
        tags: ['security.voter']
        public: true
    
    #UserVoter
    AppBundle\Security\UserVoter:
        tags: ['security.voter']
        public: true
        
    #AppsVoter
    AppBundle\Security\AppsVoter:
        tags: ['security.voter']
        public: true